name: Docker

on:
  push:
    branches: [ "dev", "npcbots_3.3.5" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/metadata-action@v4
      with:
        images: ycmk/TrinityCore-3.3.5-with-NPCBots
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/metadata-action@v4
      with:
        images: ycmk/TrinityCore-3.3.5-with-NPCBots
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
