name: Docker Build/Push

on:
  push:
    branches: [ "dev", "npcbots_3.3.5" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        push: false
        
        platforms: linux/amd64,linux/arm64

        #tags: # optional
