name: Docker

on:
  push:
    branches: [ "dev", "npcbots_3.3.5" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: false
        #tags: # optional
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64
    
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: false
        platforms: linux/arm64
        #tags: # optional
        cache-from: type=gha
        cache-to: type=gha,mode=max
