name: Docker

on:
  push:
    branches: [ "dev", "npcbots_3.3.5" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ycmk/TrinityCore-NPCBots
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable=${{is_default_branch}}
          type=raw,value=${{sha}}
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ycmk/TrinityCore-NPCBots-arm
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable=${{is_default_branch}}
          type=raw,value=${{sha}}
    - uses: docker/build-push-action@v3.2.0
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
