name: Fork Sync

on:
  #schedule:
  #  - cron: '0 8 * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: williamchai
          base: npcbots_3.3.5
          head: npcbots_3.3.5
          merge_method: merge
          retries: 1
          retry_after: 10
